services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payverify-backend
    restart: always
    ports:
      - "7001:7001"
    env_file:
      - .env
    environment:
      - PORT=7001
      - REDIS_URL=redis://default:checkbirr!162127@redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: payverify-redis
    restart: always
    command: redis-server --requirepass checkbirr!162127
    expose:
      - "6379"   # <--- Use 'expose' instead of 'ports' to avoid host port collisions
    volumes:
      - redis_data:/data

volumes:
  redis_data:
