const colors = {
  light: {
    text: "#0F172A",
    tint: "#2563EB",
    background: "#F8FAFC",
    foreground: "#0F172A",
    card: "#FFFFFF",
    cardForeground: "#0F172A",
    primary: "#2563EB",
    primaryForeground: "#FFFFFF",
    secondary: "#EFF6FF",
    secondaryForeground: "#1D4ED8",
    muted: "#F1F5F9",
    mutedForeground: "#64748B",
    accent: "#10B981",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E2E8F0",
    input: "#E2E8F0",
    warning: "#F59E0B",
    warningForeground: "#FFFFFF",
    success: "#10B981",
    successForeground: "#FFFFFF",
    suspicious: "#F59E0B",
    suspicious_bg: "#FFFBEB",
    approved_bg: "#F0FDF4",
    rejected_bg: "#FEF2F2",
  },
  dark: {
    text: "#F8FAFC",
    tint: "#3B82F6",
    background: "#0F172A",
    foreground: "#F8FAFC",
    card: "#1E293B",
    cardForeground: "#F8FAFC",
    primary: "#3B82F6",
    primaryForeground: "#FFFFFF",
    secondary: "#1E3A5F",
    secondaryForeground: "#93C5FD",
    muted: "#1E293B",
    mutedForeground: "#94A3B8",
    accent: "#10B981",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#334155",
    input: "#334155",
    warning: "#F59E0B",
    warningForeground: "#FFFFFF",
    success: "#10B981",
    successForeground: "#FFFFFF",
    suspicious: "#F59E0B",
    suspicious_bg: "#1C1400",
    approved_bg: "#052E16",
    rejected_bg: "#1F0909",
  },
  radius: 12,
};

export default colors;
